#!/bin/sh

#PBS -N RNA-LM-Rfam

#PBS -q fat-1

#PBS -l nodes=1:ppn=1 


#PBS -V

#PBS -S /bin/bash

cd /lustre/home/xhong/PostDotWorks/2023/yikun/RNA-ESM2
source ../LModel/bin/activate
# python esm_profile_test2.py
# python esm_profile_test3.py
# python esm_profile_test.py
# python esm_profile_test3.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/yikun/RNA-ESM2/All_IRES.fa produce.outname=All_IRES
# python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/RNAstrAlign/RMalignResults/allSeqs.fa produce.outname=RMalign_seqs
#python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/Pvalue/seqs/allseqs.fa produce.outname=Pvalue
# python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/xrRNA/genomes/animal/flavivirus_genome_sequences.fasta  produce.outname=flavivirus
python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/xrRNA/genomes/animal/Hepacivirus_genome.fasta produce.outname=Hepacivirus
#  python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/xrRNA/genomes/animal/Pegivirus_genome.fasta produce.outname=Pegivirus
# python esm_profile_test4.py produce.seqfile=/lustre/home/xhong/PostDotWorks/2023/BPmap-LM/xrRNA/genomes/animal/pestivirus_genome.fasta produce.outname=pestivirus
